// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwadvZqr8x_R6YsPYjeWCQs87daObXAT0',
    appId: '1:6988736338:web:9acabede3399274ae87c8b',
    messagingSenderId: '6988736338',
    projectId: 'darak-25c55',
    authDomain: 'darak-25c55.firebaseapp.com',
    storageBucket: 'darak-25c55.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ267UwKU9OVygAr29RFdNO2iNmuxgZwQ',
    appId: '1:6988736338:android:ee8075fad2c43e0de87c8b',
    messagingSenderId: '6988736338',
    projectId: 'darak-25c55',
    storageBucket: 'darak-25c55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA02qKCctrENUmuzeeA5Gv1ScH3JipmOBs',
    appId: '1:6988736338:ios:745a92050d0bae11e87c8b',
    messagingSenderId: '6988736338',
    projectId: 'darak-25c55',
    storageBucket: 'darak-25c55.firebasestorage.app',
    iosBundleId: 'com.example.darak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA02qKCctrENUmuzeeA5Gv1ScH3JipmOBs',
    appId: '1:6988736338:ios:745a92050d0bae11e87c8b',
    messagingSenderId: '6988736338',
    projectId: 'darak-25c55',
    storageBucket: 'darak-25c55.firebasestorage.app',
    iosBundleId: 'com.example.darak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwadvZqr8x_R6YsPYjeWCQs87daObXAT0',
    appId: '1:6988736338:web:8f83251743844738e87c8b',
    messagingSenderId: '6988736338',
    projectId: 'darak-25c55',
    authDomain: 'darak-25c55.firebaseapp.com',
    storageBucket: 'darak-25c55.firebasestorage.app',
  );

}